apiVersion: v1
kind: Secret
metadata:
  name: rp-users
type: Opaque
stringData:
  # Basic auth users here:
  basic.txt: |
    ABCDEFG: 123123,krp-users
    bob: bobsecret,krp-users
  # Kafka Client block is for propagation, make sure all basic auth users are ALSO defined in KafkaClient
  restProxyUsers.jaas: |
    KafkaRest {
      org.eclipse.jetty.jaas.spi.PropertyFileLoginModule required
      debug="true"
      file="/mnt/secrets/rp-users/basic.txt";
      };
    KafkaClient {
      org.apache.kafka.common.security.plain.PlainLoginModule required username="ABCDEFG" password="123123";
      org.apache.kafka.common.security.plain.PlainLoginModule required username="bob" password="bobsecret";
    };